import Footer from "@/components/Footer/footer";
import "./globals.css";
import Nav from "@/components/Navbar/nav";
import Hero from "@/components/Hero/hero";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
        <Nav/>
        <Hero/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
